version: '3'
services:

# 如果要把mysql獨立出來,則註解掉這段 , 另外執行mysql-docker-compose.yml
  database:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: twoway-database
    ports:
      - 3339:3306

  # spring:
  # # 如果將mysql獨立出來 , SPRING_DATASOURCE_URL要改為youth-database
  #   depends_on:
  #     - database
  #   image: twoway-spring
  #   restart: unless-stopped
  #   environment:
  #   # 將mysql獨立出來 , URL改為youth-database
  #     # SPRING_DATASOURCE_URL: jdbc:mysql://youth-database:3306/twowaydb
  #     SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/twowaydb
  #     SPRING_DATASOURCE_USERNAME: user
  #     SPRING_DATASOURCE_PASSWORD: 123456
  #   container_name: twoway-spring
  #   ports:
  #     - "8080:8080"

  # cms:
  #   image: twoway-react
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./react/xinwu:/app
  #   container_name: twoway-react

  mysql-backup:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./Twoway-scanner/mysqlbackup:/backup
    depends_on:
      - database
    entrypoint: >
      sh -c "
      while true; do
        mysqldump -h database -u root -p123456 --all-databases > /backup/all_databases.sql;
        sleep 21600; # 6 hours
      done
      "